name: Deploy sanchayanbd.com via SFTP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js (v20+)
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build project (Vite)
        run: npm run build

      - name: SFTP Deploy using SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SANCHAYAN_SFTP_HOST }}
          username: ${{ secrets.SANCHAYAN_SFTP_USERNAME }}
          password: ${{ secrets.SANCHAYAN_SFTP_PASSWORD }}
          port: 22
          source: "dist/*"
          target: "/home/sanchaya/public_html"
